# **1. numpy**

#### **numpy.array**
- numpy의 배열 class
- 딥러닝 구현할 때 numpy.array의 메서드 이용함.

### **1.1 numpy 가져오기**

In [12]:
import numpy as np

### **1.2 numpy 배열 생성하기**
#### **np.array()**
- numpy 배열 생성
- 인수: 파이썬의 리스트
- 반환: numpy library가 제공하는 numpy.ndarray 형태의 배열

In [28]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

### **1.3 numpy의 산술 연산**

#### **numpy 배열의 원소별 산술 연산**
주의) 배열 x, y의 원소 수 동일해야 함.

In [32]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [34]:
# 원소별(element-wise) 덧셈
x + y

array([3., 6., 9.])

In [36]:
# 원소별 곱셈 (element-wise product)
x * y

array([ 2.,  8., 18.])

In [38]:
x / y

array([0.5, 0.5, 0.5])

#### **numpy 배열과 스칼라 조합의 산술 연산**
- broadcast(브로드캐스트)

In [45]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

### **1.4 numpy의 N차원 배열**
- 1차원 배열: vector
- 2차원 배열: matrix
- tensor: 벡터와 행렬을 일반화한 것

shape: 배열의 각 차원의 크기(원소 수)

In [50]:
# 2차원 배열(행렬)
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [52]:
A.shape

(2, 2)

In [54]:
A.dtype

dtype('int32')

#### **행렬의 산술 연산**
element-wise 연산이 이뤄짐.

In [68]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0,6]])

In [70]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [73]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [75]:
# broadcast
print(A)
A * 10

[[1 2]
 [3 4]]


array([[10, 20],
       [30, 40]])

### **1.5 broadcast(브로드캐스트)**
- numpy에서는 shape이 다른 배열끼리도 계산 가능함.
- element-wise 연산이 이루어짐.

In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10,20])
A * B

array([[10, 40],
       [30, 80]])

### **1.6 원소 접근**

In [83]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [85]:
X[0]

array([51, 55])

In [87]:
X[0][1]

55

In [89]:
X[0,1]

55

X[a,b]: 교집합 느낌임. a 관련 선택한 상황에서 b 관련 선택  
X[a][b]: X[a]라는 array에서 b관련 선택

In [95]:
print(X[:,1])
print(X[:][1])

[55 19  4]
[14 19]


In [106]:
# X를 1차원 배열로 변환(평탄화)
X = X.flatten()
print(X)

[51 55 14 19  0  4]


#### **특정 조건을 만족하는 원소만 얻기**

In [108]:
# index가 0,2,4인 원소 얻기
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [113]:
X > 15

array([ True,  True, False,  True, False, False])

In [115]:
X[X>15]

array([51, 55, 19])